import React, { useState, useEffect } from 'react';
import { useNavigate, Link } from 'react-router-dom';
import API from '../services/api';
import LocationPickerMap from '../components/LocationPickerMap';
import { PlusCircle, Upload, MapPin, Tag, CheckCircle2, ShieldAlert, Sparkles, BrainCircuit, Zap, SlidersHorizontal } from 'lucide-react';

const CreateChallenge = () => {
  const navigate = useNavigate();

  // Core 3 Inputs
  const [title, setTitle] = useState('');
  const [locationInput, setLocationInput] = useState('');
  const [imageFile, setImageFile] = useState(null);
  const [imagePreview, setImagePreview] = useState('');

  // Additional metadata (Auto-generated by AI or manually edited)
  const [description, setDescription] = useState('');
  const [state, setState] = useState('');
  const [district, setDistrict] = useState('');
  const [locality, setLocality] = useState('');
  const [landmark, setLandmark] = useState('');
  const [pincode, setPincode] = useState('');
  const [coords, setCoords] = useState(null);
  const [regionType, setRegionType] = useState('Rural');
  const [category, setCategory] = useState('Water & Sanitation');
  const [severity, setSeverity] = useState('Medium');
  const [affectedCount, setAffectedCount] = useState('');
  const [affectedWho, setAffectedWho] = useState('');
  const [localContext, setLocalContext] = useState('');
  const [baselineMetric, setBaselineMetric] = useState('');
  const [evidenceFiles, setEvidenceFiles] = useState([]);
  const [similar, setSimilar] = useState([]);

  // UI modes
  const [showAdvanced, setShowAdvanced] = useState(false);
  const [aiLoading, setAiLoading] = useState(false);
  const [aiResult, setAiResult] = useState(null);
  const [aiError, setAiError] = useState('');

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');

  const handleImageChange = (e) => {
    const file = e.target.files[0];
    if (file) {
      setImageFile(file);
      setImagePreview(URL.createObjectURL(file));
    }
  };

  const handleEvidenceChange = (e) => {
    setEvidenceFiles(Array.from(e.target.files).slice(0, 4));
  };

  useEffect(() => {
    if (title.trim().length < 6) {
      setSimilar([]);
      return;
    }
    const timer = setTimeout(async () => {
      try {
        const params = new URLSearchParams({
          title: title.trim(),
          category,
        });
        if (district.trim() || locationInput.trim()) params.set('district', district.trim() || locationInput.trim());
        const res = await API.get(`/challenges/similar?${params.toString()}`);
        setSimilar(res.data || []);
      } catch (err) {
        setSimilar([]);
      }
    }, 400);
    return () => clearTimeout(timer);
  }, [title, category, district, locationInput]);

  /**
   * ⚡ 3-Input Smart AI Fast Creation & Submission
   * Auto-generates description, category, severity, and location tags before submitting.
   */
  const handleSmartAISubmit = async (e) => {
    if (e) e.preventDefault();
    setError('');
    setSuccess('');

    if (!title.trim()) {
      setError('Please enter a challenge title.');
      return;
    }
    if (!locationInput.trim() && (!state.trim() || !district.trim() || !locality.trim())) {
      setError('Please enter the location (e.g., Dumka, Jharkhand or Ward 4).');
      return;
    }
    if (!imageFile && evidenceFiles.length === 0) {
      setError('At least one ground photo evidence is required.');
      return;
    }

    setAiLoading(true);
    setLoading(true);

    try {
      // 1. Call AI engine to analyze title, location, and auto-generate fields
      const aiRes = await API.post('/challenges/ai-analyze', {
        title: title.trim(),
        location: locationInput.trim() || `${locality}, ${district}, ${state}`,
        description: description.trim(),
      });

      const aiData = aiRes.data;
      setAiResult(aiData);

      const finalDescription = description.trim() || aiData.description || `Severe issue reported at ${locationInput}: ${title}`;
      const finalCategory = category || aiData.category || 'Other';
      const finalSeverity = severity || aiData.severity || 'Medium';
      const finalState = state.trim() || aiData.state || locationInput.split(',')[2]?.trim() || 'State';
      const finalDistrict = district.trim() || aiData.district || locationInput.split(',')[1]?.trim() || 'District';
      const finalLocality = locality.trim() || aiData.locality || locationInput.split(',')[0]?.trim() || 'Local Ward';
      const finalAffectedWho = affectedWho.trim() || aiData.affectedWho || 'Local residents and school children';

      // Auto-update form state
      setDescription(finalDescription);
      setCategory(finalCategory);
      setSeverity(finalSeverity);
      setState(finalState);
      setDistrict(finalDistrict);
      setLocality(finalLocality);

      // 2. Build FormData and submit to backend
      const formData = new FormData();
      formData.append('title', title.trim());
      formData.append('description', finalDescription);
      formData.append('state', finalState);
      formData.append('district', finalDistrict);
      formData.append('locality', finalLocality);
      formData.append('landmark', landmark.trim());
      formData.append('pincode', pincode.trim());
      if (coords?.lat && coords?.lng) {
        formData.append('latitude', coords.lat);
        formData.append('longitude', coords.lng);
      }
      formData.append('regionType', regionType);
      formData.append('category', finalCategory);
      formData.append('severity', finalSeverity);
      formData.append('affectedCount', affectedCount || 100);
      formData.append('affectedWho', finalAffectedWho);
      formData.append('localContext', localContext.trim() || aiData.localContext || '');
      formData.append('baselineMetric', baselineMetric.trim() || aiData.baselineMetric || '');
      if (imageFile) {
        formData.append('image', imageFile);
      }
      evidenceFiles.forEach((file) => formData.append('evidence', file));

      const res = await API.post('/challenges', formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });

      setSuccess('✨ Smart AI auto-generated your challenge details and submitted successfully!');
      setTimeout(() => {
        navigate(`/challenges/${res.data._id}`);
      }, 1500);
    } catch (err) {
      console.error('Smart AI Submit Error:', err);
      setError(err.response?.data?.message || 'Failed to submit challenge');
    } finally {
      setAiLoading(false);
      setLoading(false);
    }
  };

  return (
    <div className="max-w-2xl mx-auto px-4 py-8">
      <div className="bg-white rounded-2xl border border-slate-200 p-8 shadow-sm">

        {/* Header */}
        <div className="mb-6 pb-4 border-b border-slate-100 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-3">
          <div>
            <div className="flex items-center gap-2 text-brand-600 font-bold text-sm mb-1 uppercase tracking-wider">
              <PlusCircle className="w-4 h-4" /> Citizen Portal
            </div>
            <h1 className="text-2xl font-extrabold text-slate-900">Report a Grassroots Challenge</h1>
            <p className="text-sm text-slate-500 mt-1">
              Provide just <strong>3 basic inputs</strong> (Title, Location, Photo)—our Smart AI handles the rest!
            </p>
          </div>
          <span className="bg-amber-100 text-amber-900 border border-amber-300 text-[11px] font-extrabold px-3 py-1 rounded-full flex items-center gap-1 shrink-0">
            <Zap className="w-3.5 h-3.5 text-amber-600" /> 3-Input AI Fast Mode
          </span>
        </div>

        {error && (
          <div className="mb-4 bg-rose-50 border border-rose-200 text-rose-700 text-sm p-3 rounded-lg flex items-center gap-2">
            <ShieldAlert className="w-4 h-4 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        {success && (
          <div className="mb-4 bg-emerald-50 border border-emerald-200 text-emerald-700 text-sm p-3 rounded-lg flex items-center gap-2">
            <CheckCircle2 className="w-4 h-4 shrink-0" />
            <span>{success}</span>
          </div>
        )}

        <form onSubmit={handleSmartAISubmit} className="space-y-6">

          {/* 1. Challenge Title */}
          <div>
            <label className="block text-xs font-bold text-slate-800 uppercase tracking-wider mb-1 flex items-center justify-between">
              <span>1. Challenge Title *</span>
              <span className="text-[10px] text-slate-400 font-normal">What is the problem?</span>
            </label>
            <input
              type="text"
              required
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g. Handpump broken near Kathikund Middle School"
              className="w-full px-4 py-2.5 text-sm border border-slate-300 rounded-xl focus:ring-2 focus:ring-brand-500 bg-slate-50/50"
            />
          </div>

          {/* Similar check */}
          {similar.length > 0 && (
            <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 space-y-2">
              <p className="text-xs font-bold text-amber-900 uppercase tracking-wider">
                Possible duplicate issue detected nearby
              </p>
              <ul className="space-y-2">
                {similar.map((item) => (
                  <li key={item._id} className="bg-white border border-amber-100 rounded-lg px-3 py-2 flex items-center justify-between gap-2">
                    <div className="min-w-0">
                      <p className="text-sm font-semibold text-slate-900 truncate">{item.title}</p>
                      <p className="text-[11px] text-slate-500 truncate">{item.location} · {item.votesCount || 0} votes</p>
                    </div>
                    <Link to={`/challenges/${item._id}`} className="shrink-0 text-xs font-bold text-brand-700 hover:underline">
                      Open existing
                    </Link>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* 2. Location Input */}
          <div>
            <label className="block text-xs font-bold text-slate-800 uppercase tracking-wider mb-1 flex items-center justify-between">
              <span>2. Location *</span>
              <span className="text-[10px] text-slate-400 font-normal">Village/Ward, District, State</span>
            </label>
            <div className="relative">
              <MapPin className="w-4 h-4 text-rose-500 absolute left-3.5 top-3" />
              <input
                type="text"
                required
                value={locationInput}
                onChange={(e) => setLocationInput(e.target.value)}
                placeholder="e.g. Ward 4, Dumka, Jharkhand"
                className="w-full pl-10 pr-4 py-2.5 text-sm border border-slate-300 rounded-xl focus:ring-2 focus:ring-brand-500 bg-slate-50/50"
              />
            </div>
          </div>

          {/* 3. Photo Evidence Upload */}
          <div>
            <label className="block text-xs font-bold text-slate-800 uppercase tracking-wider mb-1 flex items-center justify-between">
              <span>3. Ground Photo Evidence *</span>
              <span className="text-[10px] text-slate-400 font-normal">Photo of the spot</span>
            </label>
            <div className="border-2 border-dashed border-slate-300 rounded-xl p-5 text-center hover:border-brand-500 transition-colors bg-slate-50/50">
              <input
                type="file"
                accept="image/*"
                onChange={handleImageChange}
                className="hidden"
                id="challenge-image-upload"
              />
              <label htmlFor="challenge-image-upload" className="cursor-pointer flex flex-col items-center gap-2">
                <Upload className="w-8 h-8 text-slate-400" />
                <span className="text-xs font-bold text-brand-600">Click to upload photo evidence</span>
                <span className="text-[11px] text-slate-400">PNG, JPG, WEBP up to 5MB</span>
              </label>

              {imagePreview && (
                <div className="mt-3 rounded-lg overflow-hidden h-40 max-w-sm mx-auto border border-slate-200 shadow-sm">
                  <img src={imagePreview} alt="Preview" className="w-full h-full object-cover" />
                </div>
              )}
            </div>
          </div>

          {/* Fast Submit Button */}
          <div className="pt-2">
            <button
              type="submit"
              disabled={loading || aiLoading}
              className="w-full py-3.5 px-6 bg-gradient-to-r from-amber-500 via-amber-400 to-amber-500 hover:from-amber-400 hover:to-amber-300 text-slate-950 font-black rounded-xl shadow-md transition-all flex items-center justify-center gap-2 text-sm disabled:opacity-50"
            >
              {loading || aiLoading ? (
                <>Analyzing & Creating Challenge via AI...</>
              ) : (
                <>
                  <BrainCircuit className="w-5 h-5 text-slate-950 animate-pulse" />
                  ✨ Smart AI Auto-Generate & Submit Challenge
                </>
              )}
            </button>
          </div>

          {/* AI Result Card if generated */}
          {aiResult && (
            <div className="bg-slate-900 text-white p-4 rounded-xl text-xs space-y-2 border border-slate-800">
              <div className="flex items-center justify-between">
                <span className="text-amber-300 font-extrabold flex items-center gap-1">
                  <Sparkles className="w-4 h-4 text-amber-400" /> AI Auto-Generated Metadata
                </span>
                <span className="px-2 py-0.5 rounded bg-emerald-500 text-slate-950 font-bold uppercase text-[10px]">
                  {aiResult.severity} Severity
                </span>
              </div>
              <p className="text-slate-300"><strong className="text-white">Category:</strong> {aiResult.category}</p>
              <p className="text-slate-300"><strong className="text-white">Generated Description:</strong> "{aiResult.description}"</p>
            </div>
          )}

          {/* Toggle Advanced / Manual Options */}
          <div className="pt-4 border-t border-slate-100">
            <button
              type="button"
              onClick={() => setShowAdvanced(!showAdvanced)}
              className="text-xs font-bold text-slate-500 hover:text-brand-600 flex items-center gap-1.5 transition-colors mx-auto"
            >
              <SlidersHorizontal className="w-3.5 h-3.5" />
              {showAdvanced ? 'Hide Advanced / Manual Form Fields' : 'Show Advanced / Manual Form Fields (Optional)'}
            </button>
          </div>

          {/* Advanced Optional Fields */}
          {showAdvanced && (
            <div className="space-y-6 pt-4 border-t border-slate-100 bg-slate-50 p-5 rounded-2xl">

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">
                    Category (Optional Override)
                  </label>
                  <div className="relative">
                    <Tag className="w-4 h-4 text-slate-400 absolute left-3 top-3" />
                    <select
                      value={category}
                      onChange={(e) => setCategory(e.target.value)}
                      className="w-full pl-9 pr-4 py-2.5 text-sm border border-slate-300 rounded-lg bg-white"
                    >
                      <option value="Water & Sanitation">Water & Sanitation</option>
                      <option value="Education">Education</option>
                      <option value="Infrastructure">Infrastructure</option>
                      <option value="Health">Health</option>
                      <option value="Environment">Environment</option>
                      <option value="Governance">Governance</option>
                      <option value="Other">Other</option>
                    </select>
                  </div>
                </div>

                <div>
                  <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">
                    Severity (Optional Override)
                  </label>
                  <select
                    value={severity}
                    onChange={(e) => setSeverity(e.target.value)}
                    className="w-full px-4 py-2.5 text-sm border border-slate-300 rounded-lg bg-white"
                  >
                    <option value="Low">Low</option>
                    <option value="Medium">Medium</option>
                    <option value="High">High</option>
                    <option value="Critical">Critical</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">
                  Detailed Description (Optional Manual Override)
                </label>
                <textarea
                  rows={3}
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="Leave empty to let AI generate automatically..."
                  className="w-full px-4 py-2.5 text-sm border border-slate-300 rounded-lg bg-white"
                />
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <input
                  value={locality}
                  onChange={(e) => setLocality(e.target.value)}
                  placeholder="Village / Ward"
                  className="px-3 py-2 text-sm border border-slate-300 rounded-lg bg-white"
                />
                <input
                  value={district}
                  onChange={(e) => setDistrict(e.target.value)}
                  placeholder="District"
                  className="px-3 py-2 text-sm border border-slate-300 rounded-lg bg-white"
                />
                <input
                  value={state}
                  onChange={(e) => setState(e.target.value)}
                  placeholder="State"
                  className="px-3 py-2 text-sm border border-slate-300 rounded-lg bg-white"
                />
              </div>

              <div className="pt-2">
                <LocationPickerMap
                  initialLat={coords?.lat}
                  initialLng={coords?.lng}
                  onChange={(pos) => setCoords(pos)}
                />
              </div>

              <div>
                <label className="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-1">
                  Additional Evidence Photos (Optional, up to 4)
                </label>
                <input
                  type="file"
                  accept="image/*"
                  multiple
                  onChange={handleEvidenceChange}
                  className="w-full text-xs text-slate-500 file:mr-3 file:py-2 file:px-3 file:rounded-lg file:border-0 file:text-xs file:font-semibold file:bg-brand-50 file:text-brand-700"
                />
              </div>

            </div>
          )}

        </form>

      </div>
    </div>
  );
};

export default CreateChallenge;
